### ISSUE TITLE
[FR]: Integrate schelp-watcher

### ISSUE THREAD

**Issue by madskjeldgaard** [davidgranstrom/scnvim#111]
**Is your feature request related to a problem? Please describe.**
I recently discovered @elgiano's really nice schelp-watch script (https://github.com/elgiano/schelp-watch) for live rerendering of schelp files while editing them. I think the potential for integrating this somehow in scnvim is awesome as it makes live rendering of help files really nice and simple.

I have integrated it into my own neovim setup using the following commands
**Describe the solution you'd like**
In the example below is what I have done so far in my own setup. Assuming `schelp-watch` is in your path, the following executes schelp-watch from the context of current directory on pressing Ctrl-e:

```vim

" Set filetype to schelp when entering help file for editing
autocmd BufNewFile,BufRead *.schelp set filetype=schelp

"" Uses https://github.com/elgiano/schelp-watch
function! g:WatchSCHelp()
	" Get path to current file names directory
    let l:file_path=expand('%:p:h')
    execute 'vsplit term://schelp-watch ' . file_path . ' -o'
endfunction

function! SCHelpBindings()

	nnoremap <C-e> :execute WatchSCHelp()<cr>
	inoremap <C-e> <esc>:execute WatchSCHelp()<cr>
endfunction

autocmd filetype schelp call SCHelpBindings()

```

**Additional context**

See this issue for additional context on schelp filetype
https://github.com/davidgranstrom/scnvim/issues/110

**Comment by elgiano** [comment]
Hi @madskjeldgaard 
I'm super happy you are using schelp-watch and like it! You should know however that it's quite experimental, and it probably hasn't been widely used by anyone else than us two, as far as I know.

So, I'm super happy to receive feedback about it, and I would give it a bit of love before integrating it in other platforms <3
For example, today I just added a feature to make it easier to work with main sc's git repo. It shouldn't change anything for your use-case though, but that is only because after I read this post I decided not to change the interface :).
Any problems, bugs or questions, feel free to write me or to open an issue.

Great to see it bound to vim shortcuts btw :)

**Comment by madskjeldgaard** [comment]
> Hi @madskjeldgaard
> I'm super happy you are using schelp-watch and like it! You should know however that it's quite experimental, and it probably hasn't been widely used by anyone else than us two, as far as I know.
> 
> So, I'm super happy to receive feedback about it, and I would give it a bit of love before integrating it in other platforms <3
> For example, today I just added a feature to make it easier to work with main sc's git repo. It shouldn't change anything for your use-case though, but that is only because after I read this post I decided not to change the interface :).
> Any problems, bugs or questions, feel free to write me or to open an issue.
> 
> Great to see it bound to vim shortcuts btw :)

Cool! It's probably best to keep this out of scnvim for now. I might make a small plugin for it though cause it's really useful!
