### ISSUE TITLE
[FR]: Add command for manually echoing args

### ISSUE THREAD

**Issue by madskjeldgaard** [davidgranstrom/scnvim#113]
I would love a feature that would let you manually (re)echo args from a method. as it is now, `scnvim#util#echo_args()` is called by an autocmd, but at least I cannot retrigger this manually using `:call scnvim#util#echo_args()` (or maybe every time the cursor passes over a method?)

**Comment by madskjeldgaard** [comment]
ping @salkin-mada

**Comment by davidgranstrom** [comment]
@madskjeldgaard I was planning on reimplementing this in a more robust way with this feature in mind, but since I haven't had much time lately to work on scnvim I think it would make sense to backport this feature to the existing codebase. I would accept a PR for this if someone would have the time. This is basically all there is to it

https://github.com/davidgranstrom/scnvim/blob/topic/arghints-lua/autoload/scnvim/util.vim#L13-L20

And then switch out the autocmd to call `scnvim#util#echo_args_insert()` instead.

**Comment by davidgranstrom** [comment]
@madskjeldgaard I opened a PR implementing this feature. The default keybinding is `C-k` for normal/insert mode to echo the function signature. The cursor needs to be on/inside the left most bracket depending on how the code is nested. Please let me what you think know if you try it out!
