### ISSUE TITLE
[BUG] Error at opening Help

### ISSUE THREAD

**Issue by mesjetiu** [davidgranstrom/scnvim#191]
**Describe the bug**
Ctrl+k or `:SCNvimHelp <command>` does not open help. Instead, I get this message:
```
[scnvim] Could not find g:scnvim_scdoc_render_prg                                               
Se ha detectado un error al procesar function scnvim#help#open_help_for:
línea   15
E121: Undefined variable: cmd

```

**Expected behavior**
Normaly, it should open a new buffer with help doc.

**Information**

- Operating system
Manjaro Linux x86_64  (updated)
kernel: 5.15.41-1-MANJARO
DE: GNOME 42.1
Terminal: gnome-terminal

- SuperCollider version
3.12.2

- `nvim --version`
```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilado por builduser
```

- Package manager
vim-plug

**Comment by ranjithshegde** [comment]
> ```
> [scnvim] Could not find g:scnvim_scdoc_render_prg                                               
> Se ha detectado un error al procesar function scnvim#help#open_help_for:
> ```
The error says it could not find `scdoc_render_prg`

What does your scnvim setup look like? 
If you have the following variable declared `let g:scnvim_scdoc = 1` then scnvim will try to render the Help files in vim buffer.
 
But, for it to convert the HTML files into text files in order to render it, it will need an executable  which is (usually, if not always) pandoc. Do you have pandoc installed?

**Comment by mesjetiu** [comment]
Yes. It was only this... It was necessary Pandoc. Now it works normaly.
Thank you very much!
