### ISSUE TITLE
[BUG] Error executing vim.schedule lua callback: […] Unrecognized handler

### ISSUE THREAD

**Issue by ckutzner** [davidgranstrom/scnvim#209]
**Describe the bug**
After booting the SuperCollider server, I get the following error message: 
![2022-12-29_scnvim-bug](https://user-images.githubusercontent.com/12252378/209983886-15876afa-594e-47fc-b918-a0521c602be7.png)

**Expected behavior**

**Steps to reproduce**

**Additional context**
I reinstalled scnvim after running into this bug repeatedly while trying to transition to lua config from older versions. The error persist after reinstalling and using the default config.

**Information**

- Operating system
Windows 10 Version 10.0.19044

- SuperCollider version
3.13.0-rc1

- `nvim --version`
0.8.1

- Package manager
Packer

- checkhealth output
```
scnvim: require("scnvim.health").check()
========================================================================
## scnvim
  - OK: nvim version 0.8.1
  - OK: sclang executable: C:/Program Files/SuperCollider/sclang.exe
  - OK: scnvim classes are installed: C:/Users/User/AppData/Local/SuperCollider/Extensions/scide_scnvim
  - OK: keymaps are defined

## scnvim documentation
  - INFO: using HelpBrowser for documentation

## scnvim extensions
```

**Comment by davidgranstrom** [comment]
@ckutzner Thanks for the report. Perhaps older versions of the scnvim SuperCollider classes are still installed since you mention that you are updating to a new configuration? Try and manually delete `C:/Users/User/AppData/Local/SuperCollider/Extensions/scide_scnvim` and then restart Neovim, this would ensure that the latest classes installed (if you are using the default scnvim configuration). Please let me know if the error still persists!

**Comment by ckutzner** [comment]
Thank you, that fixed it, it works now!
