### ISSUE TITLE
[FR]: Send commands to remote sclang

### ISSUE THREAD

**Issue by triss** [davidgranstrom/scnvim#237]
I'm working on a Bela Pepper and would love to be able to run not just server code but language code remotely.

In a dream world I'd also see a post window showing the results of the evaluation on the other machine

I'm considering seeing if it's possible to connect via SSH but running nvim on the system is unlikely to be as comfortable as what I have set up on the Desktop.

Is it possible to have scnvim talk to sclang on another machine?

**Comment by davidgranstrom** [comment]
This is not supported out-of-the-box, since the sclang process is spawned by nvim and and (sc) code is sent via `stdin`.

With that said, it could be possible to set up something up by overriding a couple of scnvim's [actions](https://davidgranstrom.github.io/scnvim/modules/scnvim.action.html). You would probably need to create some type of wrapper script such as [this](https://github.com/davidgranstrom/sclang-lsp-stdio) to start the sclang process on the remote machine. You would then create some overrides, e.g. `editor.on_send` action to send your (sc) code to the remote instance. It will take some work for sure, but would be interesting to know if you succeed! It could perhaps become something we could add to the wiki, or maybe even create a dedicated [extension](https://github.com/davidgranstrom/scnvim?tab=readme-ov-file#extensions).

**Comment by triss** [comment]
Thanks for the pointers! May well take a look over the coming weeks.
