### ISSUE TITLE
make scnvim work without a graphical env

### ISSUE THREAD

**Issue by wobbol** [davidgranstrom/scnvim#27]
This isn't really a bug more of an enhancement.
`sclang` will only run in a graphical env. `xvfb` is an application that fakes a graphical env. It is used by the supercollider team for one of their tests [here](https://github.com/supercollider/supercollider/blob/f65a1ef7bfb100f4ccb7dcab3a6dff6826be4344/testsuite/sclang/launch_test.py#L38)
Using this info, I wrote a work around that works like a charm, but I don't know how/if you want me to work this into your codebase.
my hack is just adding `'xvfb-run'` to the beginning of the job.cmd [here](https://github.com/davidgranstrom/scnvim/blob/1a8071fbb75e3fc520a31963163ba9eac2edd1cd/autoload/scnvim/sclang.vim#L69)

I went a little further and wrote a toggle for this into `settings.run_env.nogui` and made a user config option named `g:scnvim_nogui` but, it doesn't feel like the way you would do it.

I am willing to do a little work on this as a pull request, if you are interested. I just need some feedback about how you want this implemented.

**Comment by davidgranstrom** [comment]
Hi @wobbol and thank you for your interest in scnvim!

I didn't know about this issue, but I'm glad that you found a workaround. I'm a bit hesitant of adding an additional option/switch since there is already starting to be quite a lot of these in the code base. It would be very good though to provide a solution for this problem, maybe we could create a new section in the help docs if we find a workaround outside of modifying the scnvim source code?

I haven't tried this myself, but could another workaround be to compile SuperCollider `-DSC_QT=OFF`?

Also, would it be possible to wrap `sclang` in a shell script which does something like (untested)
```shell
#!/bin/sh

xvfb-run && exec ./sclang $*
```
..and then use`let g:scnvim_sclang_executable = 'path/to/xfvb_sclang` to point to that script?
