### ISSUE TITLE
[Question]: Increase font size in qt Help Browser ?

### ISSUE THREAD

**Issue by paum3** [davidgranstrom/scnvim#79]
Hi, it is possibile ?
thank you

**Comment by davidgranstrom** [comment]
@paum3 Hi!

Yes, you can create a `custom.css` file and place it in `Platform.helpDir` (execute `Platform.helpDir` in SuperCollider to get the path). From there you could override all styling of the HelpBrowser. For example:

**custom.css**
```
body {
  font-size: 16px;
}
```

**Comment by paum3** [comment]
aha. ok. so there is no way to adjust it "on the fly", true?
thank you

**Comment by davidgranstrom** [comment]
Not that I know of. Here is a hack that you can try. It would have been cleaner with a class extension instead of a subclass, but unfortunately there is no way to define new class/instance variables in class extensions, so it had to be subclassed.. 

Add `ZoomableHelpBrowser.sc` to your Extensions and bind the vim script function to a key of your choice. You can then resize the WebView using `Ctrl +` and `Ctrl -`. I think I might send this upstream and see if it could be included in the default `HelpBrowser` implementation instead.

**ZoomableHelpBrowser.sc**
```supercollider
ZoomableHelpBrowser : HelpBrowser {
    classvar savedKeyDownAction;
    *extOpen {|subject|
        var browser = super.instance;
        savedKeyDownAction = savedKeyDownAction ?? { browser.window.view.keyDownAction };
        // use Ctrl +/- to zoom in/out
        browser.window.view.keyDownAction = {arg view, char, mods, uni, kcode, key;
            var webview, zoom;
            var zoomAmount = 0.1;
            if (key == 43 && mods.isCtrl) { // +
                webview = view.children.select {|v| v.class == WebView }.first;
                if (webview.notNil) {
                    zoom = webview.zoom;
                    webview.zoom = zoom + zoomAmount;
                };
            };
            if (key == 45 && mods.isCtrl) { // -
                webview = view.children.select {|v| v.class == WebView }.first;
                if (webview.notNil) {
                    zoom = webview.zoom;
                    webview.zoom = zoom - zoomAmount;
                };
            };
            savedKeyDownAction.(view, char, mods, uni, kcode, key);
        };
        super.openHelpFor(subject);
    }
}
```

And then add this to your `init.vim`

```vim
function! OpenHelpBrowser()
  let cmd = 'ZoomableHelpBrowser.extOpen("' . expand('<cword>') . '")'
  call scnvim#sclang#send_silent(cmd) 
endfunction

nnoremap K :call OpenHelpBrowser()<cr>
```

**Comment by paum3** [comment]
Wow David! That looks promising. I will try it tomorrow. it is interesting
to see  that there is an access within sc. Thank you sir

**Comment by paum3** [comment]
it works. it is great. thank you david.

best

**Comment by davidgranstrom** [comment]
This feature is now [merged](https://github.com/supercollider/supercollider/pull/4932) to SuperCollider develop branch.
