### ISSUE TITLE
[Question]:  run SC code from Help Browser

### ISSUE THREAD

**Issue by paum3** [davidgranstrom/scnvim#81]
Hi, would it be possible? I thik it's a great feature of SCIDE.
best
paum

**Comment by davidgranstrom** [comment]
@paum3 That is something beyond the scope of the scnvim project at the moment I'm afraid, but I think it should work if it was implemented upstream (in the SuperCollider repository). You might want to try scnvim's internal documentation system otherwise. You will need to install [pandoc](https://pandoc.org/) and set `let g:scnvim_scdoc = 1` to enable this. You can read more about it in `:h scnvim-help-system`
