### ISSUE TITLE
[FR]: use what ever binary to convert html to txt

### ISSUE THREAD

**Issue by salkin-mada** [davidgranstrom/scnvim#85]
**Is your feature request related to a problem? Please describe.**
haskell and arm dont play nice. pandoc is out of the question. 

**Describe the solution you'd like**
the user should be able to set the `let` `scnvim_pandoc_executable` and specify a parser string for the argument construction to `.unixCmdGetStdOut`.
instead of hardcoding it to `pandoc`

**Describe alternatives you've considered**
opening it with :sp | term<c>i and w3m or even python2-html2text

**Additional context**
live coding auditory mayhem headlessly on arm device via ssh.

**Comment by davidgranstrom** [comment]
Good suggestion! We could maybe introduce a `g:scnvim_scdoc_render_prg` which could default to pandoc (i.e. the current behaviour).

Something I've also considered is to actually write a scdoc parser in lua, that would mean that no external deps are needed at all in order to display scdoc helpfiles in nvim. I think that this could be done relatively easy using the `lpeg` module.
